# Generated by Django 3.1.6 on 2025-11-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf', '0003_blacklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.TextField(default='')),
                ('proxy_host', models.TextField(default='0.0.0.0')),
                ('proxy_port', models.IntegerField(default=8080)),
                ('real_host', models.TextField(default='127.0.0.1')),
                ('real_port', models.IntegerField(default=80)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
