# Generated by Django 4.2.26 on 2025-11-06 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waf', '0005_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('SQLI', 'SQL注入'), ('XSS', 'XSS跨站'), ('CSRF', 'CSRF'), ('RCE', '命令执行'), ('OTHER', '其他规则')], default='OTHER', max_length=10, verbose_name='规则类型'),
        ),
        migrations.AddField(
            model_name='rule',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='action',
            field=models.CharField(choices=[('BLOCK', '拦截'), ('LOG', '记录'), ('PASS', '放行')], default='BLOCK', max_length=10, verbose_name='动作'),
        ),
    ]
