# Generated by Django 4.2.26 on 2025-11-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf', '0006_rule_created_at_rule_rule_type_rule_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/', verbose_name='头像'),
        ),
    ]
