# Generated by Django 4.2.26 on 2025-11-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf', '0007_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.svg', null=True, upload_to='avatars/', verbose_name='头像'),
        ),
    ]
