# Generated by Django 3.2.11 on 2025-12-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf', '0008_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='reason',
            field=models.TextField(blank=True, default='', verbose_name='触发原因'),
        ),
        migrations.AddField(
            model_name='log',
            name='rule_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='规则ID'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('SQLI', 'SQL注入'), ('XSS', 'XSS跨站'), ('CSRF', 'CSRF'), ('RCE', '命令执行'), ('SSRF', 'SSRF'), ('PTR', '路径遍历'), ('UPLOAD', '文件上传'), ('OTHER', '其他规则')], default='OTHER', max_length=10, verbose_name='规则类型'),
        ),
    ]
