# Generated by Django 3.2.11 on 2026-03-17 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waf', '0009_auto_20251226_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='权限代码')),
                ('name', models.CharField(max_length=100, verbose_name='权限名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='权限描述')),
                ('category', models.CharField(default='其他', max_length=50, verbose_name='权限分类')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
            },
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('SQLI', 'SQL注入'), ('XSS', 'XSS跨站'), ('CSRF', 'CSRF'), ('RCE', '命令执行'), ('SSRF', 'SSRF'), ('XXE', 'XXE'), ('DESER', '反序列化'), ('PTR', '路径遍历'), ('UPLOAD', '文件上传'), ('OTHER', '其他规则')], default='OTHER', max_length=10, verbose_name='规则类型'),
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='授权时间')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waf.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户权限',
                'verbose_name_plural': '用户权限',
                'unique_together': {('user', 'permission')},
            },
        ),
    ]
