# Generated by Django 3.2.11 on 2026-03-17 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waf', '0010_auto_20260317_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('operation_type', models.CharField(choices=[('CREATE', '创建'), ('UPDATE', '修改'), ('DELETE', '删除'), ('LOGIN', '登录'), ('LOGOUT', '登出'), ('OTHER', '其他')], max_length=20, verbose_name='操作类型')),
                ('module', models.CharField(default='', max_length=100, verbose_name='操作模块')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='对象ID')),
                ('object_name', models.CharField(default='', max_length=200, verbose_name='对象名称')),
                ('operation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('ip_address', models.CharField(default='', max_length=50, verbose_name='IP地址')),
                ('details', models.TextField(blank=True, default='', verbose_name='操作详情')),
                ('status', models.CharField(choices=[('SUCCESS', '成功'), ('FAILED', '失败')], default='SUCCESS', max_length=20, verbose_name='操作状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-operation_time'],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登录时间')),
                ('ip_address', models.CharField(default='', max_length=50, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='用户代理')),
                ('status', models.CharField(choices=[('SUCCESS', '成功'), ('FAILED', '失败')], default='SUCCESS', max_length=20, verbose_name='登录状态')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'ordering': ['-login_time'],
            },
        ),
    ]
